### ISSUE TITLE
living_street

### ISSUE THREAD

**Issue by ghost** [raintonr/mkgmap-bike-onroad#2]
Hi

Living_street does not appear in my onroad Garmin map. Is it due to something missing in osm database, or is it due to the custom map, which does not consider living_street as a route?

Because it's a useful cycling route

My example https://www.openstreetmap.org/way/1127115753

**Comment by raintonr** [comment]
These types of route probably need adding to bike-onroad/lines. PR's welcome :)

**Comment by ghost** [comment]
done

**Comment by raintonr** [comment]
Fixed in #3

**Comment by ghost** [comment]
Thanks! Do you know when it will be effective on garmin.bbbike.org ?

**Comment by raintonr** [comment]
Sorry, I am nothing to do with that site so have no idea.
